# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 22:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=250, unique_for_date='dt')),
                ('dt', models.DateTimeField(default=datetime.datetime(2017, 3, 16, 22, 24, 56, 678978, tzinfo=utc))),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=50)),
                ('intstates', models.CharField(max_length=2)),
            ],
            options={
                'ordering': ('-dt',),
            },
        ),
    ]
