# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 22:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0002_auto_20170316_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 16, 22, 33, 11, 523986, tzinfo=utc)),
        ),
    ]
