# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0003_auto_20170316_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
